### ISSUE TITLE
Wish: basic usage documentation

### ISSUE THREAD

**Issue by markstos** [SheetJS/js-harb#5] opened 2015-01-28 17:07 UTC
Currently the README punts users to read the documentation on XLS parsing to see how this CSV parser works. There's a lot of XLS-specific stuff there that doesn't apply here. There the docs show that parsing is done through a global variable named  XLS. We might assume that the corresponding variable used here is named CSV, since it's not documented, but it's apparently named HARB instead. 

It's details like this that make it valuable to have more complete documentation on how the CSV parsing works in this project.

**Comment by SheetJSDev** [comment] 2015-01-28 18:02
tl;dr: I agree, it's in the pipeline.

FWIW this module was intended to provide support for the `j` command line tool: https://www.npmjs.com/package/j , and we were surprised to find people using it directly.  In our minds, this was a temporary solution until all of the licensing concerns were resolved, at which point all of the modules would be merged into one (js-sheet or whatever).  As is usually the case, that process is taking much longer than expected and I agree that some documentation here would help in the interim.

**Comment by SheetJSDev** [comment] 2017-12-04 06:07
We've merged this module into [js-xlsx](https://github.com/SheetJS/js-xlsx), and at this point there is no need to consume HARB directly.

**Closed by SheetJSDev** 2017-12-04 06:07 UTC
